# -*- coding: utf-8 -*-
"""train_6people.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dA1XGMKZZWS9am6KExUOgTugD03k4Tcd
"""

from google.colab import drive
drive.mount('/content/drive')

import os

PROJECT_PATH = '/content/drive/MyDrive/Final_project_gesture'
DATASET_PATH = f'{PROJECT_PATH}/dataset'
MODELS_PATH = f'{PROJECT_PATH}/models'

os.makedirs(MODELS_PATH, exist_ok=True)

print('DATASET_PATH:', DATASET_PATH)
print('MODELS_PATH:', MODELS_PATH)
print(sorted(os.listdir(DATASET_PATH)))

!pip install -q keras==3.12.3

import numpy as np
import tensorflow as tf

os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

gpus = tf.config.list_physical_devices('GPU')
print('GPU devices:', gpus)
if not gpus:
    print('\n' + '!' * 70)
    print('GPU가 없습니다. 지금 상태로 학습하면 CPU로 돌아 몇 배 느립니다.')
    print('런타임 > 런타임 유형 변경 > 하드웨어 가속기 > T4 GPU 로 바꾸고')
    print('이 노트북을 처음부터 다시 실행하세요.')
    print('!' * 70)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile hand_feature.py
# 
# import numpy as np
# 
# ACTIONS = ['idle', 'print', 'zoom', 'select']
# SEQ_LENGTH = 30
# FEATURE_DIM = 78
# COLLECT_SIZE = (480, 270)        # 16:9. 4:3 카메라면 (480, 360)
# COLLECT_ASPECT = COLLECT_SIZE[0] / COLLECT_SIZE[1]
# INFER_SIZE = COLLECT_SIZE
# ASPECT = COLLECT_ASPECT
# 
# def aspect_of(width, height):
#     return width / height
# 
# _V1_IDX = [0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 11, 0, 13, 14, 15, 0, 17, 18, 19]
# _V2_IDX = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# _A_IDX = [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18]
# _B_IDX = [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19]
# 
# def normalize_joints(joints, aspect=ASPECT):
#     j = np.array(joints, dtype=np.float32, copy=True)
#     j[..., 0] *= aspect
#     j[..., 2] *= aspect
#     j = j - j[..., 0:1, :]
#     scale = np.linalg.norm(j[..., 9, :], axis=-1, keepdims=True)
#     scale = np.maximum(scale, 1e-6)[..., np.newaxis]
#     return j / scale
# 
# def angles_from_joints(joints):
#     j = np.asarray(joints, dtype=np.float32)
#     v = j[..., _V2_IDX, :] - j[..., _V1_IDX, :]
#     n = np.linalg.norm(v, axis=-1, keepdims=True)
#     v = v / np.maximum(n, 1e-6)
#     dot = np.sum(v[..., _A_IDX, :] * v[..., _B_IDX, :], axis=-1)
#     angle = np.arccos(np.clip(dot, -1.0, 1.0))       # radian, 0~pi
#     return (angle / np.pi).astype(np.float32)
# 
# 
# def make_feature(joints, aspect=ASPECT, already_normalized=False):
#     jn = joints if already_normalized else normalize_joints(joints, aspect)
#     coords = np.asarray(jn, dtype=np.float32).reshape(*np.shape(jn)[:-2], 63)
#     angles = angles_from_joints(jn)
#     return np.concatenate([coords, angles], axis=-1)
# 
# def joints_from_landmarks(res):
#     j = np.zeros((21, 3), dtype=np.float32)
#     for i, lm in enumerate(res.landmark):
#         j[i] = [lm.x, lm.y, lm.z]
#     return j
# 
# def joints_from_raw(rows):
#     r = np.asarray(rows, dtype=np.float32)
#     return r[..., :84].reshape(*r.shape[:-1], 21, 4)[..., :3]
# 
# def labels_from_raw(rows):
#     return np.asarray(rows, dtype=np.float32)[..., -1].astype(np.int64)

import shutil
shutil.copy('hand_feature.py', f'{PROJECT_PATH}/hand_feature.py')
print('Drive에도 복사 완료 ->', f'{PROJECT_PATH}/hand_feature.py')

from hand_feature import ACTIONS, SEQ_LENGTH, COLLECT_SIZE, COLLECT_ASPECT
print('ACTIONS      :', ACTIONS)
print('COLLECT_SIZE :', COLLECT_SIZE, f'(aspect {COLLECT_ASPECT:.4f})')
print('\ncreate_dataset.py 의 infer_size 와 같은지 확인하세요.')

import glob, re
from collections import defaultdict

SECS_FOR_ACTION = 30      # create_dataset.py 와 동일하게
CAPTURE_FPS = 15          # ★ create_dataset.py 가 출력한 '평균 실측 fps'
SEQ_STRIDE = 1            # 데이터가 넉넉하지 않으므로 전부 사용

pat = re.compile(r'^seq_(?P<action>[a-z_]+?)(?:_p(?P<person>\d+))?_(?P<ts>\d+)\.npy$')

raw_by_person = defaultdict(list)
table = defaultdict(int)
fps_est = {}

paths = [p for a in ACTIONS for p in sorted(glob.glob(f'{DATASET_PATH}/seq_{a}_*.npy'))]

for p in paths:
    m = pat.match(os.path.basename(p))
    if not m:
        print('[skip] 이름 형식이 다름:', os.path.basename(p)); continue
    action = m.group('action')
    person = int(m.group('person') or 0)
    if action not in ACTIONS:
        print('[skip] ACTIONS 에 없는 동작:', action); continue

    arr = np.load(p).astype(np.float32)
    if arr.size == 0 or arr.shape[1] != SEQ_LENGTH:
        print('[경고] 비었거나 길이 불일치:', os.path.basename(p), arr.shape); continue

    fps_est[(person, action)] = (len(arr) + SEQ_LENGTH - 1) / SECS_FOR_ACTION
    arr = arr[::SEQ_STRIDE]
    raw_by_person[person].append(arr)
    table[(person, action)] += len(arr)

raw_by_person = {k: np.concatenate(v) for k, v in raw_by_person.items()}
persons = sorted(raw_by_person)

print('\n사람 x 동작 시퀀스 수')
print('        ' + ''.join(f'{a:>10s}' for a in ACTIONS) + f'{"합계":>10s}')
for p in persons:
    row = [table[(p, a)] for a in ACTIONS]
    print(f'P{p:<7d}' + ''.join(f'{v:>10d}' for v in row) + f'{sum(row):>10d}')
tot = [sum(table[(p, a)] for p in persons) for a in ACTIONS]
print('합계    ' + ''.join(f'{v:>10d}' for v in tot) + f'{sum(tot):>10d}')

print(f'\n윈도우 {SEQ_LENGTH}프레임 = {SEQ_LENGTH / CAPTURE_FPS:.2f}초 '
      f'(수집 {CAPTURE_FPS}fps 기준)')
print(f'-> gesture_pip.py 의 TRAIN_FPS 를 {CAPTURE_FPS} 로 맞춰야 합니다.')

print('\n유효 프레임 기준 추정 fps (손 검출 실패가 많으면 낮게 나온다)')
for p in persons:
    v = [fps_est.get((p, a), 0) for a in ACTIONS]
    flag = '' if min(v) > CAPTURE_FPS * 0.75 else '   <- 검출률 낮음, 재촬영 검토'
    print(f'  P{p}: ' + '  '.join(f'{a}={x:4.1f}' for a, x in zip(ACTIONS, v)) + flag)

if len(persons) == 1 and persons[0] == 0:
    print('\n[문제] 모든 파일이 P0 입니다. create_dataset.py 의 PERSON 을')
    print('       1~6 으로 바꿔가며 촬영해야 사람 단위 분할이 가능합니다.')

missing = [(p, a) for p in persons for a in ACTIONS if table[(p, a)] == 0]
if missing:
    print('\n[문제] 빠진 조합:', ', '.join(f'P{p}-{a}' for p, a in missing))

from hand_feature import normalize_joints, make_feature, joints_from_raw

FEAT_MODE = 'norm'          # 'norm' | 'legacy'
AUG_COPIES = 2              # 증강 사본 수 (legacy 모드에서는 무시)
rng = np.random.default_rng(1209)


def augment(j, rng):
    """(N,T,21,3) 정규화 좌표 증강. 반전/회전은 시퀀스 단위로 동일하게."""
    j = j.copy(); n = len(j)
    flip = rng.random(n) < 0.5
    j[flip, ..., 0] *= -1                                    # 좌우 반전 (각도는 불변)
    th = rng.uniform(-np.pi/9, np.pi/9, size=n).astype(np.float32)
    cs, sn = np.cos(th)[:, None, None], np.sin(th)[:, None, None]
    x, y = j[..., 0], j[..., 1]
    j[..., 0], j[..., 1] = cs*x - sn*y, sn*x + cs*y          # 화면 내 회전 +-20도
    j *= rng.uniform(0.9, 1.1, size=(n, 1, 1, 1)).astype(np.float32)
    j += rng.normal(0, 0.02, size=j.shape).astype(np.float32)
    return j


def to_features(raw, aug_rng=None):
    if FEAT_MODE == 'legacy':
        return raw[..., :99].astype(np.float32)
    # 수집 해상도의 화면비로 편다 (hand_feature.COLLECT_ASPECT 기본값)
    jn = normalize_joints(joints_from_raw(raw))
    if aug_rng is not None:
        jn = augment(jn, aug_rng)
    return make_feature(jn, already_normalized=True).astype(np.float32)


def labels_of(raw):
    return raw[:, 0, -1].astype(np.int64)


FEATURE_DIM = 78 if FEAT_MODE == 'norm' else 99
print('FEAT_MODE =', FEAT_MODE, ' FEATURE_DIM =', FEATURE_DIM)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.utils import to_categorical


def build_model(feature_dim):
    m = Sequential([
        Input(shape=(SEQ_LENGTH, feature_dim)),
        LSTM(64, return_sequences=True),
        Dropout(0.3),
        LSTM(64),
        Dropout(0.3),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(len(ACTIONS), activation='softmax'),
    ])
    m.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    return m


build_model(FEATURE_DIM).summary()

from sklearn.model_selection import train_test_split


def fit_eval(x_tr, y_tr, x_va, y_va, tag, epochs=100):
    model = build_model(x_tr.shape[-1])
    model.fit(x_tr, to_categorical(y_tr, len(ACTIONS)),
              validation_data=(x_va, to_categorical(y_va, len(ACTIONS))),
              epochs=epochs, batch_size=128, verbose=0,
              callbacks=[
                  EarlyStopping(monitor='val_acc', mode='max', patience=20,
                                restore_best_weights=True),
                  ReduceLROnPlateau(monitor='val_acc', mode='max',
                                    factor=0.5, patience=8, min_lr=1e-5),
              ])
    acc = (model.predict(x_va, verbose=0).argmax(1) == y_va).mean()
    print(f'{tag:32s} val acc = {acc*100:6.2f}%')
    return acc


all_raw = np.concatenate([raw_by_person[p] for p in persons])
x_all, y_all = to_features(all_raw), labels_of(all_raw)

xa, xb, ya, yb = train_test_split(x_all, y_all, test_size=0.1,
                                  random_state=2021, stratify=y_all)
acc_random = fit_eval(xa, ya, xb, yb, '(A) 랜덤 분할 (기존 방식)')

if len(persons) >= 2:
    vp = persons[-1]
    tr = [p for p in persons if p != vp]
    r_tr = np.concatenate([raw_by_person[p] for p in tr])
    acc_person = fit_eval(to_features(r_tr), labels_of(r_tr),
                          to_features(raw_by_person[vp]), labels_of(raw_by_person[vp]),
                          f'(B) P{vp} 통째로 제외')
    print(f'\n부풀려진 양: {(acc_random - acc_person)*100:+.2f}%p')
    print('(B) 가 실제 성능입니다. (A) 만 보고 판단하면 안 됩니다.')
else:
    print('\n사람이 1명뿐이라 (B) 를 못 합니다. 6명 촬영 후 다시 실행하세요.')

VAL_PERSON = persons[-1] if len(persons) >= 2 else None

train_persons = [p for p in persons if p != VAL_PERSON]
raw_tr = np.concatenate([raw_by_person[p] for p in train_persons])
y_tr = labels_of(raw_tr)

xs, ys = [to_features(raw_tr)], [y_tr]
if FEAT_MODE == 'norm':
    for _ in range(AUG_COPIES):
        xs.append(to_features(raw_tr, rng)); ys.append(y_tr)
x_train = np.concatenate(xs); y_train = np.concatenate(ys)
del xs, ys

idx = rng.permutation(len(x_train))
x_train, y_train = x_train[idx], y_train[idx]

if VAL_PERSON is not None:
    x_val = to_features(raw_by_person[VAL_PERSON])          # 검증에는 증강 없음
    y_val = labels_of(raw_by_person[VAL_PERSON])
    val_data = (x_val, to_categorical(y_val, len(ACTIONS)))
else:
    x_val = y_val = val_data = None

counts = np.bincount(y_train, minlength=len(ACTIONS))
class_weight = {i: float(len(y_train)/(len(ACTIONS)*max(cnt, 1)))
                for i, cnt in enumerate(counts)}

print('학습:', train_persons, ' 검증:', VAL_PERSON)
print('x_train', x_train.shape, ' x_val', None if x_val is None else x_val.shape)
print('class_weight', {ACTIONS[i]: round(w, 2) for i, w in class_weight.items()})

VERSION = 'v5'
ckpt = f'{MODELS_PATH}/model.{VERSION}.{FEAT_MODE}.keras'
monitor = 'val_acc' if val_data else 'acc'

model = build_model(FEATURE_DIM)

history = model.fit(
    x_train, to_categorical(y_train, len(ACTIONS)),
    validation_data=val_data,
    epochs=200, batch_size=128, class_weight=class_weight,
    callbacks=[
        ModelCheckpoint(ckpt, monitor=monitor, mode='max',
                        save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor=monitor, mode='max', factor=0.5,
                          patience=8, min_lr=1e-5, verbose=1),
        EarlyStopping(monitor=monitor, mode='max', patience=25,
                      restore_best_weights=True, verbose=1),
    ])

import matplotlib.pyplot as plt

fig, loss_ax = plt.subplots(figsize=(16, 8))
acc_ax = loss_ax.twinx()

loss_ax.plot(history.history['loss'], 'y', label='train loss')
acc_ax.plot(history.history['acc'], 'b', label='train acc')
if val_data:
    loss_ax.plot(history.history['val_loss'], 'r', label='val loss')
    acc_ax.plot(history.history['val_acc'], 'g', label='val acc')

loss_ax.set_xlabel('epoch'); loss_ax.set_ylabel('loss')
loss_ax.legend(loc='upper left')
acc_ax.set_ylabel('accuracy'); acc_ax.legend(loc='lower left')
plt.show()

from sklearn.metrics import confusion_matrix

if val_data is not None:
    y_pred = model.predict(x_val, verbose=0).argmax(1)
    print(f'처음 보는 사람(P{VAL_PERSON}) 정확도: {(y_pred == y_val).mean()*100:.2f}%\n')

    cm = confusion_matrix(y_val, y_pred, labels=list(range(len(ACTIONS))))
    print('혼동행렬 (행=정답, 열=예측)')
    print(' ' * 12 + ''.join(f'{a:>10s}' for a in ACTIONS) + f'{"재현율":>10s}')
    for i, a in enumerate(ACTIONS):
        recall = cm[i, i] / max(cm[i].sum(), 1) * 100
        print(f'  {a:10s}' + ''.join(f'{cm[i, j]:10d}' for j in range(len(ACTIONS)))
              + f'{recall:9.1f}%')

    print('\n특정 행만 낮으면 그 동작이 다른 동작과 겹치는 것이고,')
    print('전체가 고르게 낮으면 사람 다양성이 부족한 것입니다.')
else:
    print('VAL_PERSON=None 이라 검증을 건너뜁니다 (배포용 학습).')

import json

model.save(ckpt)
w_path = f'{MODELS_PATH}/model.{VERSION}.{FEAT_MODE}.weights.h5'
model.save_weights(w_path)

meta = {
    'version': VERSION,
    'feature_mode': FEAT_MODE,
    'feature_dim': FEATURE_DIM,
    'actions': ACTIONS,
    'seq_length': SEQ_LENGTH,
    'capture_fps': CAPTURE_FPS,
    'window_seconds': SEQ_LENGTH / CAPTURE_FPS,
    'collect_size': list(COLLECT_SIZE),
    'collect_aspect': COLLECT_ASPECT,
    'train_persons': train_persons,
    'val_person': VAL_PERSON,
}
json.dump(meta, open(f'{MODELS_PATH}/model.{VERSION}.{FEAT_MODE}.json', 'w'), indent=2)
print('저장 완료')
print(' ', ckpt)
print(' ', w_path)

print('=' * 62)
print('gesture_pip.py 에 이대로 맞추세요')
print('=' * 62)
print(f"FEAT_MODE       = '{FEAT_MODE}'")
print(f"MODEL_WEIGHTS   = 'models/model.{VERSION}.{FEAT_MODE}.weights.h5'")
print(f"ACTIONS         = {ACTIONS}")
print(f"SEQ_LENGTH      = {SEQ_LENGTH}")
print(f"FEATURE_DIM     = {FEATURE_DIM}")
print(f"TRAIN_FPS       = {float(CAPTURE_FPS)}")
print(f"# INFER 해상도 화면비는 {COLLECT_ASPECT:.4f} 여야 합니다")
print(f"#   -> 320x180, 480x270, 640x360 중 아무거나 (모두 16:9)")
print()
print('함께 복사할 파일')
print(f'  {w_path}')
print(f'  {PROJECT_PATH}/hand_feature.py')
print()
print('그리고 gesture_pip.py 의 build_model() 이 이 노트북과 같은지 확인:')
print('  Input -> LSTM(64, return_sequences=True) -> Dropout(0.3)')
print('        -> LSTM(64) -> Dropout(0.3)')
print('        -> Dense(32, relu) -> Dropout(0.2) -> Dense(4, softmax)')
print('=' * 62)